const customError = (message) => {
    this.message = message;
    this.name = 'UserException';
  }